version: "3.4"
services:
  nginx:
    image: nginx:1.24.0-alpine
    container_name: '${COMPOSE_PROJECT_NAME}-nginx'
    volumes:
      - ./docker/nginx/config/ssl:/etc/nginx/certs
      - ./docker/nginx/config/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${DOCKER_PROJECT_IP}:80:80"
      - "${DOCKER_PROJECT_IP}:443:443"
    depends_on:
      - app
    healthcheck:
      test: service nginx status || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
  app:
    container_name: '${COMPOSE_PROJECT_NAME}-app'
    build:
      context: .
      target: app_dev
      args:
        - DOCKER_RUNTIME=${DOCKER_RUNTIME:-docker}
        - DOCKER_GID=${DOCKER_GID:-1000}
        - DOCKER_UID=${DOCKER_UID:-1000}
    restart: "no"
    volumes:
      - php_socket:/var/run/php
      - ./app:/var/www/html
    healthcheck:
      test: cgi-fcgi -bind -connect 127.0.0.1:9000 || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    ports:
      - "${DOCKER_PROJECT_IP}:9000:9000"
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  php_socket:
