services:
  app:
    container_name: '${PROJECT_NAME}-app'
    build:
      context: .
      target: app_dev
      args:
        - DOCKER_RUNTIME=${DOCKER_RUNTIME:-docker}
        - DOCKER_GID=${DOCKER_GID:-1000}
        - DOCKER_UID=${DOCKER_UID:-1000}
    restart: "no"
    volumes:
      - ./app:/var/www/html
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    ports:
      - "${DOCKER_PROJECT_IP:-127.0.0.1}:8000:8000"
    extra_hosts:
      - host.docker.internal:host-gateway
volumes:
  php_socket: