services:
  '###{service_name}###':
    container_name: '${PROJECT_NAME}-###{service_name}###'
    image: ${PROJECT_NAME}-###{service_name}###:dev
    build:
      context: .
      target: '###{service_name}###_dev'
      args:
        - DOCKER_RUNTIME=${DOCKER_RUNTIME:-docker}
        - DOCKER_GID=${DOCKER_GID:-1000}
        - DOCKER_UID=${DOCKER_UID:-1000}
    restart: "no"
    volumes:
      - './###{service_name}###:/var/www/html'
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    ports:
      - "${DOCKER_PROJECT_IP:-127.0.0.1}:8000:8000"
    extra_hosts:
      - host.docker.internal:host-gateway